### ISSUE TITLE
3.1.1 用脚本修改，手工修改都无效

### ISSUE THREAD

**Issue by winterlac1988** [kailous/Notion-client-CN#1]
如题。 mac m1 系统版本 14.1.1

**Comment by kailous** [comment]
脚本运行的截图有吗？看看是否有报错。

**Comment by winterlac1988** [comment]
> 脚本运行的截图有吗？看看是否有报错。

![WX20240121-093101@2x](https://github.com/kailous/Notion-client-CN/assets/130549366/93dc5e40-30be-49c3-aa46-c9bf561d6012)

**Comment by kailous** [comment]
看起来是没有获取到你的操作系统，我先检查下代码。

**Comment by winterlac1988** [comment]
> 看起来是没有获取到你的操作系统，我先检查下代码。

我把你的脚本放到本地运行是又是这样了。 但是也是没有打印出系统，但是看后面的逻辑是 可以判断出是macos的。
![1](https://github.com/kailous/Notion-client-CN/assets/130549366/03470c48-12ff-425e-8b6d-79119ba357fb)

**Comment by kailous** [comment]
我看了下，可能是脚本的顺序有问题 导致的信息显示问题，但是不影响脚本的运行。已经替换成功了。你尝试一下在notion客户端界面按shift + cmd + R 强制刷新一下缓存，再次运行脚本看看。

**Comment by kailous** [comment]
哦对了 因为替换的语言是英语的，所以你要先切换到英文，然后强制刷新缓存，再汉化。

**Comment by winterlac1988** [comment]
试过了。 还是不行.  我重新卸载安装了一遍 然后 按照你说的流程 还是没有变化. 语言地区默认就是en-us的。 强制刷新没效果。 版本3.1.1
<img width="311" alt="image" src="https://github.com/kailous/Notion-client-CN/assets/130549366/029f7732-4431-4e99-be77-e41036c2a795">

**Comment by winterlac1988** [comment]
网上找了一个3.1.0的版本， https://github.com/Reamd7/notion-zh_CN/releases/tag/3.1.0  用这个就汉化正常了。 感谢。

**Comment by kailous** [comment]
> 网上找了一个3.1.0的版本， https://github.com/Reamd7/notion-zh_CN/releases/tag/3.1.0 用这个就汉化正常了。感谢。

我就是这个没有用 所以才写了个脚本 哈哈哈 好迷啊
